### PR TITLE
Add command `check:links`

### PR DESCRIPTION
**Pull request by ghost**
Hey there,
the provided `getkirby/cli` command is rather big, and depending on internal links being included or not, its output can get quite long.

From the options, just a quick overview of the most important things:
- `-e` / `--external` includes only external links in the output (by default, internal links are included as well)
- `-j` / `--json` outputs, .. well, JSON
- `-f`/ `--force` requests are cached for a short amount of time, this flag forces cache refresh
- `-s`/ `--strict` strict mode exits on page rendering throwing any kind of `Exception` 

Everything else is documented by using `kirby check:links --help` as always and inside the source code, so I didn't update the README to include any of the CLI options, hoping that's alright with you.

Let me know if that's something you'd consider merging!

Cheers
CHE1RON

### CODE REVIEW

**Comment by ghost** [comment]
// Edit:
Your `composer.json` contained invalid JSON (comma at end of `author` object), so I fixed it, too - if this doesn't get merged, it should be fixed nonetheless 😉

**Comment by afbora** [comment]
@CHE1RON @S1SYPHOS Thanks for the PR. Sorry for the delay. A more comprehensive PR than I expected, and not parts that I understand much. Therefore, I think it would be better to continue with a separate plugin in terms of development and maintenance. What do you think?

**Comment by S1SYPHOS** [comment]
Alright then! I totally understand that maintaining foreign code takes up too much time in a situation like this - alright then, thanks for considering it ;)

**Comment by ghost** [comment]
As this is resolved as `wontfix`, I'll maintain this separately, have a good day, @afbora!

**Pull request closed without merging**
